### ISSUE TITLE
Cavas in Tabsheet looses content

### ISSUE THREAD

**Issue by thomasletsch** [hezamu/vaadincanvas#7]
A canvas component inside a tab does not get restored correctly when the tab was unselected and re-selected again.

Example:
@SuppressWarnings("serial")
public class Tabsheet_testUI extends UI {

```
@Override
protected void init(VaadinRequest request) {
    final VerticalLayout layout = new VerticalLayout();
    layout.setMargin(true);
    setContent(layout);
    TabSheet tabSheet = new TabSheet();
    Canvas firstCanvas = new Canvas();
    Canvas secondCanvas = new Canvas();
    tabSheet.addComponent(firstCanvas);
    tabSheet.addComponent(secondCanvas);
    firstCanvas.arc(0, 0, 10, 0, 7, false);
    firstCanvas.setFillStyle("red");
    firstCanvas.fill();
    secondCanvas.arc(0, 0, 10, 0, 7, false);
    secondCanvas.setFillStyle("blue");
    secondCanvas.fill();

    layout.addComponent(tabSheet);
}
```

}

**Comment by russellhoff** [comment]
I've got the same problem.

I've got a piece of a webpage where I show content. There, in the upper part, I've a TabSheet. What I do when selected one or another tab is hidding some components and showing only one (these components are placed below TabSheet).

Initially, the canvas is shown but, when accessing another tab and coming back to where Canvas should be, there is nothing drawed. I've been able to see that the CanvasConnector still exists when there are no canvas visible. Besides, it's possible to select the canvas.

**Comment by aymannedaa** [comment]
I'm having the same issue

**Comment by aymannedaa** [comment]
My work around was to add LayoutClickEvent to the parent component holding the Canvas and call the  function that draws the canvas there, like this:

parentComponent.addLayoutClickListener(new LayoutClickListener() {
		
			@Override
			public void layoutClick(LayoutClickEvent event) {
                         //redraw canvas
                         }
                   });

You can have other listeners (eg. selectedTabListener) depending on your case.

**Comment by hezamu** [comment]
This issue is most likely caused by layout changes updating the size of the element. The specification states that the canvas will be cleared when this happens, there is not much the add-on can do in this case. 

The workaround is to detect the size changes (eg. using Vaadin API) and redraw when this happens. See eg. @aymannedaa's solution.
